spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    database: rideshare
    auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
  username: ${SPRING_MAIL_USERNAME}
  password: ${SPRING_MAIL_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

server:
  port: 8080
  servlet:
    context-path: /api

frontend:
  origin: ${FRONTEND_ORIGIN:http://localhost:5173}
